version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command:
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=logshuttle -t logshuttle .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar logshuttle
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Run tests
          command: |
            docker run app go test -v ./shuttle
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
              docker tag logshuttle "docker.io/akkeris/logshuttle:${CIRCLE_SHA1}"
              docker tag logshuttle "docker.io/akkeris/logshuttle:latest
              docker push "docker.io/akkeris/logshuttle:${CIRCLE_SHA1}"
              docker push "docker.io/akkeris/logshuttle:latest
            fi