version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t logshuttle .
      - run:
          name: Run tests
          command: |
            docker run logshuttle go test -v ./shuttle
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" != "release" ]; then
              docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
              docker tag logshuttle "docker.io/akkeris/logshuttle:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
              docker push "docker.io/akkeris/logshuttle:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker tag logshuttle "docker.io/akkeris/logshuttle:release-${CIRCLE_BUILD_NUM}"
                docker tag logshuttle "docker.io/akkeris/logshuttle:latest"
                docker push "docker.io/akkeris/logshuttle:latest"
                docker push "docker.io/akkeris/logshuttle:release-${CIRCLE_BUILD_NUM}"
              fi
            fi